# Utiliser une image de base PHP
FROM php:7.4-apache

# Installer Git
RUN apt-get update && apt-get install -y git

# Cloner le dépôt GitHub
RUN git clone https://github.com/ngocksam/backend.git /var/www/html/

# Exposer le port 80
EXPOSE 80
